shell = "C:\\Program Files\\PowerShell\\7\\pwsh.exe"
working_directory ="C:\\Users\\shi"

[window]
dimensions = { columns = 130, lines = 35 }
position = { x = 850, y = 390 }

[selection]
save_to_clipboard = true

[cursor]
style = {blinking = "On"}

